module.exports = {
  autocompleteHandler: require("./autocomplete"),
  automodHandler: require("./automod"),
  buttonHandler: require("./button"),
  commandHandler: require("./command"),
  contextHandler: require("./context"),
  counterHandler: require("./counter"),
  greetingHandler: require("./greeting"),
  inviteHandler: require("./invite"),
  // lavaclientEventsHandler: require("./lavaclientEvents"),
  modalHandler: require("./modal"),
  presenceHandler: require("./presence"),
  reactionRoleHandler: require("./reactionRoles"),
  selectMenuHandler: require("./selectMenu"),
  statsHandler: require("./stats"),
  suggestionHandler: require("./suggestion"),
  ticketHandler: require("./ticket"),
  translationHandler: require("./translation"),
};
